Ext.define('Klickakart.klickakart.smartdevice.com.shop.view.shoppingcontext.retail.TemplateOfItem', {
     "xtype": "templateOfItem",
     "items": [{
          "xtype": "panel",
          "items": [{
               "xtype": "hiddenfield",
               "fieldLabel": "itemId",
               "bindable": "itemId",
               "margin": 5,
               "name": "itemId",
               "itemId": "itemId_hiddenfield"
          }, {
               "xtype": "image",
               "name": "itemImg",
               "height": 100,
               "width": 100,
               "border": true,
               "src": AppRestUrl+"",
               "margin": 5,
               "bindable": "itemImg",
               "itemId": "itemImg_image",
               "bindSrc": "itemImg",
               "bind": {
                    "src": "{itemImg}"
               }
          }, {
               "xtype": "textfield",
               "fieldLabel": "Product",
               "margin": 5,
               "bindable": "productDesc",
               "name": "productDesc",
               "itemId": "productDesc_textfield"
          }, {
               "xtype": "textfield",
               "fieldLabel": "Item",
               "margin": 5,
               "bindable": "itemName",
               "name": "itemName",
               "itemId": "itemName_textfield"
          }, {
               "xtype": "numberfield",
               "fieldLabel": "Price",
               "name": "itemPrice",
               "margin": 5,
               "bindable": "itemPrice",
               "itemId": "itemPrice_numberfield"
          }, {
               "xtype": "numberfield",
               "fieldLabel": "Quantity",
               "name": "qty",
               "margin": 5,
               "bindable": "qty",
               "itemId": "qty_numberfield",
               "value": "0"
          }, {
               "xtype": "button",
               "name": "addToCart",
               "text": "Add To Cart",
               "margin": 5,
               "itemId": "addToCart_button",
               "listeners": {
                    "click": "onAddToCartClick"
               }
          }],
          "margin": 5,
          "border": true,
          "autoScroll": true,
          "itemId": "panel_ext_29704",
          "dockedItems": []
     }],
     "border": true,
     "autoScroll": true,
     "margin": 5,
     "itemId": "form_ext_29695",
     "dockedItems": [],
     "extend": "Ext.form.Panel",
     "requires": ["Klickakart.klickakart.smartdevice.com.shop.controller.shoppingcontext.retail.TemplateOfItemController", "Klickakart.klickakart.shared.com.shop.viewmodel.shoppingcontext.retail.TemplateOfItemViewModel", "Klickakart.klickakart.shared.com.shop.model.shoppingcontext.retail.TemplateOfItemModel"],
     "viewModel": "TemplateOfItemViewModel",
     "controller": "TemplateOfItemController"
});