DROP TABLE IF EXISTS `ast_OrderDetail_TP`;

CREATE TABLE `ast_OrderDetail_TP` ( `orderId` VARCHAR(256) NOT NULL, `detId` VARCHAR(256) NOT NULL, `itemId` VARCHAR(256) NOT NULL, `qty` INT(10) NOT NULL, `subTotal` DOUBLE(21,2) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(10) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(10) NULL DEFAULT NULL, PRIMARY KEY (`detId`));

